name = "consistency-rate"
compatibility_date = "2024-10-07"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "66333de5f3804dba88295ff619529d99"
